{
  config,
  pkgs,
  lib,
  ...
}:

{
  home = {
    packages = with pkgs; [
      statix
    ];

    # Simple git pre-commit hook for ~/.nixpkgs (no pre-commit framework needed)
    activation.installPreCommitHooks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            HOOKS_DIR="$HOME/.nixpkgs/.git/hooks"
            if [ -d "$HOME/.nixpkgs/.git" ]; then
              mkdir -p "$HOOKS_DIR"
              cat > "$HOOKS_DIR/pre-commit" << 'HOOK'
      #!/usr/bin/env bash
      # Auto-generated by home-manager - runs nixfmt and statix on staged .nix files

      # Get staged .nix files
      staged_nix_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$' || true)

      if [ -z "$staged_nix_files" ]; then
        exit 0
      fi

      echo "Running nixfmt..."
      echo "$staged_nix_files" | xargs nixfmt --check || {
        echo "nixfmt check failed. Run 'nixfmt <file>' to fix."
        exit 1
      }

      echo "Running statix..."
      statix check . || {
        echo "statix check failed."
        exit 1
      }

      echo "All checks passed!"
      HOOK
              chmod +x "$HOOKS_DIR/pre-commit"
            fi
    '';
  };
}
